### ISSUE TITLE
Apps Version Report - Space in app name - Forbidden, You don't have permission to access this resource.

### ISSUE THREAD

**Issue by davisriglsd** [munkireport/munkireport-php#1524]
Having issues with data in reports when the app to track has a space in the name. Which is most Adobe products, DetectX Swift, Cricut Design Space and a few others. The apps will appear in the Apps Version Report with no data. Clicking on the menu to show "known versions of the app" results in a page that says "Forbidden. You don't have permission to access this resource."

If I change my .yml file and replace the space with an underscore the apps list will show the various versions available in the module, but then clicking on the menu or any of the versions available to see the devices results in an empty list.

Before: (with space)
```
0:
    app1: {appName: "Adobe Acrobat", widget: "app"}
    app2: {appName: "Adobe Acrobat Reader DC", widget: "app"}
    app25: {appName: "Creative Cloud", widget: "app"}
```
Result: <img width="460" alt="with space" src="https://github.com/munkireport/munkireport-php/assets/112841769/294a4dc7-6c63-48f1-947a-8044b3c7495b">

After: (without space)

```
0:
    app1: {appName: "Adobe_Acrobat", widget: "app"}
    app2: {appName: "Adobe_Acrobat_Reader_DC", widget: "app"}
    app25: {appName: "Creative_Cloud", widget: "app"}
```
Result: <img width="462" alt="with_underscore" src="https://github.com/munkireport/munkireport-php/assets/112841769/2c642be9-3374-4076-a9cf-42d50a513dba">

<img width="972" alt="no data in table" src="https://github.com/munkireport/munkireport-php/assets/112841769/0b05be96-a5d1-4ef7-821e-a64f9d051aa9">
